### ISSUE TITLE
(SP: 1) Add validation for checkbox "I confirm that I am over 18 years old"

### ISSUE THREAD

**Issue by YaroslavChuiko** [Space2Study-UA-1156/Client-01#290]
- [ ]  validate checkbox "I confirm that I am over 18 years old" as a required field on stepper data submit

![Image](https://github.com/Space2Study-UA-1156/Client-01/assets/32570823/2918e371-7704-4966-bde9-c96e9b3905b4)

**Comment by holus-bolus** [comment]
Already implemented in the PR with the mobile markup
