### ISSUE TITLE
[Login popup] The user closes Login popup by clicking outside of this popup

### ISSUE THREAD

**Issue by vlad-khrychov** [Space2Study-UA-1156/Client-01#79]
**Environment**: Windows10 21H2, Chrome 112.0.5615.138
**Reproducible**: always

**Preconditions**

The user enters Login popup window by clicking Login button  in the upper right corner of the header

**Steps to reproduce**

Click outside of the Login popup

**Actual result**

Login popup window closes

**Expected result**

Nothing should happen

**Comment by YaroslavLys** [comment]
This bug is no longer relevant and can't be reproduced
